import {StyleSheet} from 'react-native';

export const darkHomepage = StyleSheet.create({
  screenView: {
    flex: 1,
    backgroundColor: '#181823',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    overflow: 'hidden',
    alignItems: 'center',
    paddingBottom: 429,
  },
  line: {
    width: 200,
    height: 5,
    backgroundColor: 'white',
    alignSelf: 'center',
    marginVertical: 15,
    borderRadius: 5,
  },
  bar: {
    width: 300,
    height: 30,
    backgroundColor: '#FFFFF',
    alignSelf: 'center',
  },
  name: {
    height: 110,
    backgroundColor: '#537FE7',
    paddingTop: 15,
    paddingLeft: 25,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
  },
  nameText: {
    color: '#E9F8F9',
    fontSize: 30,
    fontWeight: '700',
    fontFamily: 'Jost',
    textTransform: 'uppercase',
  },
  helloText: {
    color: '#E9F8F9',
    fontSize: 30,
    fontFamily: 'Jost',
  },
  flexRow: {
    paddingTop: 15,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reminderRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  swipe: {
    fontSize: 14,
    fontWeight: '600',
    color: '#EFF3F5',
  },
  remindersText: {
    fontSize: 16,
    color: '#EFF3F5',
    fontWeight: '700',
  },
  sortContainer: {
    flexDirection: 'row',
    width: 134,
    height: 40,
    padding: 10,
    justifyContent: 'space-between',
    backgroundColor: '#273B4A',
    borderWidth: 1,
    borderColor: '#BBBBC5',
    borderRadius: 8,
  },
  sortText: {
    fontSize: 16,
    color: '#EFF3F5',
  },
  reminderContainer: {
    marginTop: 10,
    width: 344,
    height: 475,
    backgroundColor: '#273B4A',
    borderRadius: 10,
  },
  flexRow: {
    paddingTop: 15,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reminderSection: {
    height: 100,
    width: 310,
    backgroundColor: 'white',
    borderRadius: 10,
    marginTop: 10,
    marginLeft: 10,
  },
  reminderName: {
    color: '#537FE7',
    fontWeight: '600',
    fontSize: 20,
  },
  dateContainer: {
    height: 30,
    width: 80,
    backgroundColor: '#EFF3F5',
    borderRadius: 4,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  date: {
    color: '#537FE7',
    fontSize: 15,
  },
  descriptionContainer: {
    height: 58,
    width: 220,
  },
  recurringContainer: {
    height: 58,
    width: 80,
    flex: 1,
    alignItems: 'center',
  },
  caretDown: {
    width: 0,
    height: 0,
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderBottomWidth: 12,
    borderStyle: 'solid',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'black',
  },
});
